language: c++

os: osx

osx_image:
  - xcode9.4 # Xcode 9.4.1; macOS 10.13
  - xcode10.2 # Xcode 10.2.1; macOS 10.14

compiler: clang

before_install:
  - brew update

script:
  - brew tap dlr-ts/sumo
  - if [ -z "$TRAVIS_TAG" ]; then brew install -v sumo && brew test sumo; fi

### Bintray deployment ###
before_deploy:
  - echo '===> Commit was tagged with '$TRAVIS_TAG', starting bottle deployment...'
  - brew untap dlr-ts/sumo
  - brew tap dlr-ts/sumo
  - brew cask install -v xquartz
  - brew install --build-bottle -v sumo
  - brew bottle -v sumo
  - for file in $(ls sumo*bottle.tar.gz); do mv "$file" "$(echo "$file" | sed s/--/-/)"; done

deploy:
  on:
    tags: true

  provider: bintray

  file: bintray_descriptor.json

  skip_cleanup: true

  user:
    secure: Mu4l9D9zl9/ezuUJdrTwusVQUrwZth6l6IgDGwFgMwj9QbLurWUF+z7yNmyFa2zDWb3koxVY/9jFOl/4626nA0zbnbuXHe5eAe8ihVYhBBSwe24CIlN2bRIwB15sTPnOgXmwNiw3a0/9+qZzc6Uoua4kBm7gb/yqzvF2LWGwIqlYIjndw0w1e87jAb1+xOv2If6PeMzCXpnXmgUwZ2pM95QHIwNu4EL6jBCRxJJjeTuN/Rh/UM1osXeA2KMBKomRj+IvV8S3zI3wfZ7anS+yl0jacbmdq7z1BahlcdCJkHyq0duZ6/O8ESsL7/vNoq/BR0XsizItGbo7WYd1mpjFzLRug4cQyQwg+JNhQ0w76zU8Iuihk03ywcJ3r9CNRJi/mmGNG6eQ/4ixl5WOgOkfSjQpzY3gO1jVcW6MaTptfu+SfE8zG0S9J52NcJaR7ZL7DWR+Xs4XxfJ6E9EBwwqiMFSgtsKXnBD0hcaNGHByEZji6DxxRCewkcBeSj8dgXLf0XSNA+fp5REiwLBIg5q5ZliaA0zSPwpTMporu1OmxUW90F0q/8LoOhwvqtvmZNtq/CRWNSK72trr4El9hyuJvEwB7WkAxPMWYpcGqtq8ZjjrG0uGJ0E6odAz4AkVKWmXEyTEQ4T/xQo1D+jkX6vta2AvyTo1eGf3cRUa5bmlRk8=
  
  key:
    secure: o8um7LNtk8lXCojpDGKUsbRwRwVKyC2DGCzc0Pvz0IBMjw34aYjPcgHCyFqAqpMiUW9DK+RFk+3+aHEJ+1W7uGcPdx/Zhj/QAfqwp6gky6D/PoPbq7bn+c6mZwRi2umdyJcIoIKyekZ5Rbus7WLoS2joda0uqvXirXnPiWA3agxCnt15Skw4VDvcgpdnc+5vZpIdYykCISBQLdRQhCbREhNXvgg1+WYm1Eg85PA2GyQwy5BeUprVxPqSgg0VZFi2LgllXAk4lg9Q5U14Yhaoqd2RMzGXSKL9by6SR7miPnJ3p2sBWgj94FIF+jVQlY+vxs0hizaSnXkkXJ0jpVKpOsIMwopLFlNtUaQeg8W22BcZYQ9DFsjAwRWH9ONmMiscBox57VoEkEx9qtOL22Xg886hJZ821MnmPilFRcDYlEjQfeOwZ6OSajnt5eI7aSaUEpWjyk2VEfQtt+ygvdGeb54aIHTOuM6gE6rstoI/ewMon78DajwdynhlJqt32OgMR100lh90TBnBsoq4KMHjdCtSSA2m+ls0x5D6Q2pDrJ4PeiJ6t4aDs8gwcr0PZwvZ3YievZHoRiUvyJCv1c+r4jsf+0aiM6ahtPXEErXSt1LtCU66IsJHkIRLgVw17sh6thXUApGy/VAW7s0l1R1WbYAU8dYSV9ok8CR2FTqu1Os=
  
  dry_run: false
