name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test-bot:
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      # Don't do a "brew upgrade" here even if homebrew complains. It is very slow and will likely fail.

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      # query whether all dependencies are bottled
      - run: brew unbottled sumo

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - name: Test install and bottle up Formula
        run: brew test-bot --only-formulae sumo

      - name: Upload bottles as artifact
        uses: actions/upload-artifact@main
        with:
          name: bottles-${{ matrix.os }}
          path: '*.bottle.*'

      - name: Upload logs as artifact
        uses: actions/upload-artifact@main
        with:
          name: logs-${{ matrix.os }}
          path: /Users/runner/Library/Logs/Homebrew/*/*
